/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Conexion.Conexion;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Serva
 */
public class Historial extends javax.swing.JFrame {

    /**
     * Creates new form Historial
     */
    
    
    private final Conexion conexionBD;
    private final long idClienteSesion;

    
    
    
    
    public Historial(Conexion conexionBD, long idClienteSesion) {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#365979"));
        this.conexionBD = conexionBD;
        this.idClienteSesion = idClienteSesion;
        mostrarHistorialOperaciones();
        
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Cuando se cierra la ventana, establecer la visibilidad de la ventana anterior como verdadera para mostrarla nuevamente
                dispose();
            }
        });
        
        
        
        
    }
    

private void mostrarHistorialOperaciones() {
        try (Connection connection = conexionBD.crearConexion();
             PreparedStatement pstmt = connection.prepareStatement("SELECT * FROM Operaciones WHERE ID_cliente = ?");
        ) {
            pstmt.setLong(1, idClienteSesion);

            try (ResultSet rs = pstmt.executeQuery()) {
                // Crear un modelo de tabla para almacenar los datos de las operaciones
                DefaultTableModel modeloTabla = new DefaultTableModel();
                modeloTabla.addColumn("ID Operación");
                modeloTabla.addColumn("Tipo de Operación");
                modeloTabla.addColumn("Monto");
                modeloTabla.addColumn("Fecha y Hora");

                while (rs.next()) {
                    // Recuperar detalles de la operación
                    int idOperacion = rs.getInt("ID_operacion");
                    String tipoOperacion = rs.getString("tipo_operacion");
                    double monto = rs.getDouble("monto");
                    Timestamp Fecha = rs.getTimestamp("Fecha");

                    // Agregar una fila con los detalles de la operación al modelo de tabla
                    Object[] fila = {idOperacion, tipoOperacion, monto, Fecha};
                    modeloTabla.addRow(fila);
                }

                // Establecer el modelo de tabla en la tablaOperaciones
                tablaOperaciones.setModel(modeloTabla);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el historial de operaciones: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOperaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("SALIR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tablaOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaOperaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaOperaciones;
    // End of variables declaration//GEN-END:variables
}
